// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlRFruTH0BX5_vxdBfAeG9KKxRpBYEew4',
    appId: '1:502204034824:web:6bc83db6096b4f7b2846bd',
    messagingSenderId: '502204034824',
    projectId: 'gardenmonitoring-33ce9',
    authDomain: 'gardenmonitoring-33ce9.firebaseapp.com',
    databaseURL: 'https://gardenmonitoring-33ce9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardenmonitoring-33ce9.firebasestorage.app',
    measurementId: 'G-4BFWCTBQ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHXgdxU3KxTf1CfvIDPtd-NLlZjj1npw4',
    appId: '1:502204034824:android:6527373e689aaee02846bd',
    messagingSenderId: '502204034824',
    projectId: 'gardenmonitoring-33ce9',
    databaseURL: 'https://gardenmonitoring-33ce9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardenmonitoring-33ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACq8sp65P2xSYYsF_ZqiepKi2OGIG8upc',
    appId: '1:502204034824:ios:c73172559f9a7d402846bd',
    messagingSenderId: '502204034824',
    projectId: 'gardenmonitoring-33ce9',
    databaseURL: 'https://gardenmonitoring-33ce9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardenmonitoring-33ce9.firebasestorage.app',
    iosBundleId: 'com.example.monitoringTanaman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACq8sp65P2xSYYsF_ZqiepKi2OGIG8upc',
    appId: '1:502204034824:ios:c73172559f9a7d402846bd',
    messagingSenderId: '502204034824',
    projectId: 'gardenmonitoring-33ce9',
    databaseURL: 'https://gardenmonitoring-33ce9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardenmonitoring-33ce9.firebasestorage.app',
    iosBundleId: 'com.example.monitoringTanaman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlRFruTH0BX5_vxdBfAeG9KKxRpBYEew4',
    appId: '1:502204034824:web:6bc83db6096b4f7b2846bd',
    messagingSenderId: '502204034824',
    projectId: 'gardenmonitoring-33ce9',
    authDomain: 'gardenmonitoring-33ce9.firebaseapp.com',
    databaseURL: 'https://gardenmonitoring-33ce9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardenmonitoring-33ce9.firebasestorage.app',
    measurementId: 'G-4BFWCTBQ1V',
  );

}